ifeq ($(OS),Windows_NT)
    EXE := .exe
	CLEAN_CMD := rmdir /S /Q build
	CREATE_BUILD_DIR := if not exist build mkdir build
else
    EXE :=
	CLEAN_CMD := rm -rf build
	CREATE_BUILD_DIR := mkdir -p build
endif

.PHONY: all clean

all: build/main$(EXE) build/magic_generator$(EXE)

build/main$(EXE): build/magic_generator$(EXE) src/main.c src/attacks.c src/board.c src/magics.c src/autogenerated-magics.c src/moves.c
	build/magic_generator$(EXE) src/autogenerated-magics
	$(CC) -o build/main$(EXE) src/main.c src/attacks.c src/board.c src/magics.c src/autogenerated-magics.c src/moves.c -O3 -std=c23

build/magic_generator$(EXE): magic_generator/main.c
	$(CREATE_BUILD_DIR)
	$(CC) -o build/magic_generator$(EXE) magic_generator/main.c -O3 -std=c23

clean:
	$(CLEAN_CMD)