ifeq ($(OS),Windows_NT)
	# ensure the usage of cmd.exe on windows
	SHELL := cmd.exe
	.SHELLFLAGS := /C
    	EXE := .exe
	CLEAN_CMD := rmdir /S /Q build
	CREATE_BUILD_DIR := if not exist build mkdir build
	# required for executing programs on every windows version
	SLASH := \\
else
    	EXE :=
	CLEAN_CMD := rm -rf build
	CREATE_BUILD_DIR := mkdir -p build
	SLASH := /
endif

.PHONY: all clean

all: build/main$(EXE) build/magic_generator$(EXE)

build/main$(EXE): build/magic_generator$(EXE) src/main.c src/attacks.c src/board.c src/autogenerated-magics.c src/moves.c
	$(CC) -o build/main$(EXE) src/main.c src/attacks.c src/board.c src/autogenerated-magics.c src/moves.c -O3 -std=c23

build/magic_generator$(EXE): magic_generator/main.c
	$(CREATE_BUILD_DIR)
	$(CC) -o build/magic_generator$(EXE) magic_generator/main.c -O3 -std=c23

src/autogenerated-magics.c: build/magic_generator$(EXE)
	.$(SLASH)build$(SLASH)magic_generator$(EXE) src/autogenerated-magics

clean:
	$(CLEAN_CMD)