#!/usr/bin/bash
# use this script if the makefile fails, do note that this performs a full rebuild every time

rm -rf build

compiler=

if [ -z "$1" ]; then
    compiler=cc
else
    compiler=$1
fi

mkdir -p build
echo building magic_generator ...

$compiler -o build/magic_generator magic_generator/main.c -O3 -std=c23

echo dumping magics ...
./build/magic_generator src/autogenerated-magics

echo building engine ...
$compiler -o build/main src/main.c src/attacks.c src/autogenerated-magics.c src/board.c src/moves.c -O3 -std=c23

echo done!