@echo off

REM use this script if the makefile fails, do note that this performs a full rebuild every time

SETLOCAL ENABLEDELAYEDEXPANSION

if "%~1"=="" (
    set COMPILER=cc
) else (
    set COMPILER=%1
)

if exist build rmdir /S /Q build
mkdir build

echo compiling magic_generator.exe ...
!COMPILER! -o build/magic_generator.exe magic_generator/main.c -std=c23 -O3

echo dumping magics ...
.\build\magic_generator src/autogenerated-magics

echo building main ...
!COMPILER! -o build/main.exe src/attacks.c src/autogenerated-magics.c src/board.c src/main.c src/moves.c -std=c23 -O3

echo done!

ENDLOCAL