#include "attacks.h"
#include "autogenerated-magics.h"

void compute_knight_attacks(uint64_t knight_attacks[64]){
    for(int i = 0; i < 64; i++){
        knight_attacks[i] = generate_knight_attack(i);
    }
}

void compute_king_attacks(uint64_t king_attacks[64]){
    for (int i = 0; i < 64; i++){
        king_attacks[i] = generate_king_attack(i);
    }
}

void compute_pawn_attacks(uint64_t pawn_attacks[2][64]){
    for(int i = 0; i < 64; i++){
        pawn_attacks[SIDE_WHITE][i] = generate_pawn_attack(i, SIDE_WHITE);
        pawn_attacks[SIDE_BLACK][i] = generate_pawn_attack(i, SIDE_BLACK);
    }
}

uint64_t generate_knight_attack(uint8_t pos){
    uint8_t x = pos % 8;
    uint8_t y = pos / 8;
    uint64_t rtn = 0;
    static const int dx[8] = { 2, 2, 1,-1,-2,-2,-1, 1 };
    static const int dy[8] = {-1, 1, 2, 2, 1,-1,-2,-2};
    for (int i = 0; i < 8; i++){
        int nx = x + dx[i];
        int ny = y + dy[i];

        if (0 <= nx && nx < 8 && 0 <= ny && ny < 8){
            rtn |= 1ULL << XY_TO_1D(nx, ny);
        }
    }

    return rtn;
}

uint64_t generate_king_attack(uint8_t pos){
    uint8_t x = pos % 8;
    uint8_t y = pos / 8;
    uint64_t rtn = 0;
    static const int dx[8] = { 0, 1, 1,  1,  0, -1, -1, -1 };
    static const int dy[8] = { 1, 1, 0, -1, -1, -1,  0,  1 };
    for(int i = 0; i < 8; i++){
        int nx = x + dx[i];
        int ny = y + dy[i];
        if (0 <= nx && nx < 8 && 0 <= ny && ny < 8){
            rtn |= 1ULL << XY_TO_1D(nx, ny);
        }
    }
    return rtn;
}

uint64_t generate_pawn_attack(uint8_t pos, uint8_t side){
    uint8_t x = pos % 8;
    uint8_t y = pos / 8;
    uint64_t rtn = 0;
    if (x > 0 && y < 7 && side == SIDE_WHITE){
        rtn |= 1ULL << XY_TO_1D((x - 1), (y + 1));
    }
    if (x > 0 && y > 0 && side == SIDE_BLACK){
        rtn |= 1ULL << XY_TO_1D((x - 1), (y - 1));
    }
    if (x < 7 && y < 7 && side == SIDE_WHITE){
        rtn |= 1ULL << XY_TO_1D((x + 1), (y + 1));
    }
    if (x < 7 && y > 0 && side == SIDE_BLACK){
        rtn |= 1ULL << XY_TO_1D((x + 1), (y - 1));
    }
    return rtn;
}

uint64_t lookup_rook_attacks(uint8_t square, uint64_t occupancy) {
    uint64_t masked = occupancy & rook_magics[square].mask;
    uint64_t i = (masked * rook_magics[square].magic) >> rook_magics[square].shift;
    return rook_magics[square].table[i];
}

uint64_t lookup_bishop_attacks(uint8_t square, uint64_t occupancy){
    uint64_t masked = occupancy & bishop_magics[square].mask;
    uint64_t i = (masked * bishop_magics[square].magic) >> bishop_magics[square].shift;
    return bishop_magics[square].table[i];
}

uint64_t lookup_queen_attacks(uint8_t square, uint64_t occupancy){
    return lookup_rook_attacks(square, occupancy) | lookup_bishop_attacks(square, occupancy);
}