#include "magics.h"
#include "attacks.h"

uint64_t RNG_state = 74378294732989241ULL;

uint64_t randu64(){
    RNG_state ^= RNG_state << 13;
    RNG_state ^= RNG_state >> 7;
    RNG_state ^= RNG_state << 17;
    return RNG_state;
}

uint64_t magic_candidate(){
    return randu64() & randu64() & randu64();
}

static inline int popcnt(uint64_t v){
    return __builtin_popcountll(v);
}

// this generates all of the possible occupancies and then computes
// the possible attacks for those occupancies to create pairs of
// an occupancy and then an attack.
int generate_occupancy_attack_pairs(
    uint8_t pos, 
    uint64_t relevant_squares_mask,
    uint64_t (*ray_fn)(uint8_t pos, uint64_t occupancy),
    uint64_t* occupancies,
    uint64_t* attacks
){
    int i = 0;
    uint64_t subset = 0;
    do {
        occupancies[i] = subset;
        attacks[i] = ray_fn(pos, subset);
        i++;
        // "iterate" over all possible orderings of the high bits in relevant_squares_mask.
        subset = (subset - relevant_squares_mask) & relevant_squares_mask;
    } while (subset != 0);
    return i;
}

uint64_t find_magic_for_square(uint64_t mask, uint64_t* occupancies, uint64_t* attacks, int table_size, uint64_t* used_table){
    int n = popcnt(mask);
    int shift = 64 - n;
    uint64_t* tried_table = malloc(sizeof(uint64_t) * table_size);
    uint8_t* filled = malloc(sizeof(uint8_t) * table_size);
    while (1){
        uint64_t candidate = magic_candidate();
        memset(filled, 0, table_size * sizeof(uint8_t));
        int success = 1;
        for (int i = 0; i < table_size; i++){
            uint64_t index = (occupancies[i] * candidate) >> shift;
            if (!filled[index]){
                filled[index] = 1;
                tried_table[index] = attacks[i];
            } else if (tried_table[index] != attacks[i]){
                success = 0;
                break;
            }
        }
        if (success){
            memcpy(used_table, tried_table, sizeof(uint64_t) * table_size);
            free(tried_table);
            free(filled);
            return candidate;
        }
    }
}

void write_magicdump_header(FILE* f){
    fprintf(f, "// this file was automatically generated by apple-chess.\n");
    fprintf(f, "#ifndef APPLE_CHESS_AUTOGENERATED_MAGICS_H_\n");
    fprintf(f, "#define APPLE_CHESS_AUTOGENERATED_MAGICS_H_\n\n");
    fprintf(f, "#include <stdint.h>\n\n");
    fprintf(f, "typedef struct {\n");
    fprintf(f, "\tuint64_t mask;\n");
    fprintf(f, "\tuint64_t magic;\n");
    fprintf(f, "\tuint64_t* table;\n");
    fprintf(f, "\tuint64_t shift;\n");
    fprintf(f, "} MagicEntry;\n\n");
    fprintf(f, "extern MagicEntry rook_magics[64];\n");
    fprintf(f, "extern MagicEntry bishop_magics[64];\n\n");
    fprintf(f, "#endif");
}

void generate_bishop_magic_entries(DumpableMagicEntry bishops[64]){
        for(int ny = 0; ny < 8; ny++){
        for (int nx = 0; nx < 8; nx++){
            uint64_t mask = generate_bishop_relevant_mask(XY_TO_1D(nx, ny));
            int n = __builtin_popcountll(mask);
            int table_size = 1 << n;
            uint64_t occupancies[4096];
            uint64_t attacks[4096];
            uint64_t* used = malloc(table_size * sizeof(uint64_t));
            int count = generate_occupancy_attack_pairs(XY_TO_1D(nx, ny), generate_bishop_relevant_mask(XY_TO_1D(nx, ny)), generate_bishop_attacks, occupancies, attacks);
            assert(count == table_size);
            uint64_t magic = find_magic_for_square(mask, occupancies, attacks, table_size, used);
            bishops[XY_TO_1D(nx, ny)] = (DumpableMagicEntry){
                .mask = mask,
                .magic = magic,
                .table = used,
                .shift = 64 - n,
                .table_size = table_size
            };
        }
    }
}

void generate_rook_magic_entries(DumpableMagicEntry rooks[64]){
        for(int ny = 0; ny < 8; ny++){
        for (int nx = 0; nx < 8; nx++){
            uint64_t mask = generate_rook_relevant_mask(XY_TO_1D(nx, ny));
            int n = __builtin_popcountll(mask);
            int table_size = 1 << n;
            uint64_t occupancies[4096];
            uint64_t attacks[4096];
            uint64_t* used = malloc(table_size * sizeof(uint64_t));
            int count = generate_occupancy_attack_pairs(XY_TO_1D(nx, ny), generate_rook_relevant_mask(XY_TO_1D(nx, ny)), generate_rook_attacks, occupancies, attacks);
            assert(count == table_size);
            uint64_t magic = find_magic_for_square(mask, occupancies, attacks, table_size, used);
            rooks[XY_TO_1D(nx, ny)] = (DumpableMagicEntry){
                .mask = mask,
                .magic = magic,
                .table = used,
                .shift = 64 - n,
                .table_size = table_size
            };
        }
    }
}