#include <stdio.h>

#include "attacks.h"
#include "magics.h"
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <assert.h>

Position pos;

void print_board(uint64_t board){
    for(int y = 0; y < BOARD_HEIGHT; y++){
        for(int x = 0; x < BOARD_WIDTH; x++){
            printf("%d ", board_get(board, x, y));
        }
        printf("\n");
    }
}

int main(int argc, char* argv[]){
    if (argc < 2){
        printf("usage: apple-chess <usage>\n");
        return 1;
    }
    if (strcmp("--dump-magics", argv[1]) != 0){
        printf("unknown usage method\n");
        printf("%s\n", argv[1]);
        return 1;
    }

    FILE* fa = fopen("autogenerated-magics.h", "w");
    write_magicdump_header(fa);
    fclose(fa);

    DumpableMagicEntry rooks[64];
    DumpableMagicEntry bishops[64];
    generate_bishop_magic_entries(bishops);
    generate_rook_magic_entries(rooks);

    FILE* f = fopen("autogenerated-magics.c", "w");
    fprintf(f, "// this file was automatically generated by apple-chess.\n");
    fprintf(f, "// all values in this file are required for the engine to run\n");
    fprintf(f, "// and changing any of these values may cause crashes\n\n");
    fprintf(f, "#include \"autogenerated-magics.h\"\n");

    for(int i = 0; i < 64; i++){
        fprintf(f, "static uint64_t rook_table_sq%d[%d] = {", i, rooks[i].table_size);
        for (int j = 0; j < rooks[i].table_size; j++){
            if (j % 5 == 0) fprintf(f, "\n\t");
            fprintf(f, "0x%016llXULL", rooks[i].table[j]);
            if (j + 1 == rooks[i].table_size){
                fprintf(f, "\n};\n");
            } else {
                fprintf(f, ", ");
            }
        }
        fprintf(f, "static uint64_t bishop_table_sq%d[%d] = {", i, bishops[i].table_size);
        for (int j = 0; j < bishops[i].table_size; j++){
            if (j % 5 == 0) fprintf(f, "\n\t");
            fprintf(f, "0x%016llXULL", bishops[i].table[j]);
            if (j + 1 == bishops[i].table_size){
                fprintf(f, "\n};\n");
            } else {
                fprintf(f, ", ");
            }
        }
        free(rooks[i].table);
        free(bishops[i].table);
    }

    fprintf(f, "MagicEntry rook_magics[64] = {\n");
    for (int i = 0; i < 64; i++){
        fprintf(f, "\t[%d] = { .mask = 0x%016llXULL, .magic = 0x%016llXULL, ", i, rooks[i].mask, rooks[i].magic);
        fprintf(f, ".table = rook_table_sq%d, .shift = %d},\n", i, rooks[i].shift);
    }
    fprintf(f, "};\n");
    fprintf(f, "MagicEntry bishop_magics[64] = {\n");
    for(int i = 0; i < 64; i++){
        fprintf(f, "\t[%d] = { .mask = 0x%016llXULL, .magic = 0x%016llXULL, ", i, bishops[i].mask, rooks[i].magic);
        fprintf(f, ".table = rook_table_sq%d, .shift = %d},\n", i, rooks[i].shift);
    }
    fprintf(f, "};\n");
    fclose(f);

    return 0;
}