#ifndef APPLE_CHESS_MOVES_H_
#define APPLE_CHESS_MOVES_H_

#include "autogenerated-magics.h"
#include "board.h"
#include "attacks.h"

#define CASTLE_WHITE 1
#define CASTLE_BLACK 2
#define CASTLE_NONE  0

typedef struct {
    uint8_t piece;
    uint8_t from;
    uint8_t to;
    uint8_t captured_piece;
} Move;

typedef struct {
    uint64_t board[12];
    uint64_t occupancy[3];
    uint8_t en_passant;

} State;

#endif